# Generated by Django 5.0.7 on 2024-08-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, default='default_photo.jpg', null=True, upload_to='profile_photos/'),
        ),
    ]
