# Generated by Django 5.0.7 on 2024-08-12 09:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_created_at_movie_likes_movie_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='likes',
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
